### ISSUE TITLE
Bug: Translate/Rotation ignores duration

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#11]
Running the following code:

```
Kinetic.fromTo(square, duration: 5.7, from: [.Rotate(-1),.Translate(-self.view.bounds.width-80,0)], to: [.Rotate(0),.Translate(0,0)]).ease(Easing.outSine).play()
```

ignores rotation and duration. Doesn't matter what rotation or duration I set, it's always the same animation

**Comment by u10int** [comment]
This was likely due to the issues with animating transforms I mentioned before. Fortunately I've been able to refactor a lot of how transforms are handled in the library and they are vastly improved. I tested several different transformation and they all worked properly, including this one you provided here and some of the others you previously had issues with.

Note that with CATransform3D, the order in which you add the transforms matters and Kinetic transform animations follow this same behavior. So in your example here, the layer will be rotated and then translated, which will affect its anchor point and may not be the intended behavior. I think you may be after something more like this where the .Rotate and .Translate order is reversed:

```
Kinetic.fromTo(square, duration: 5.7, from: [ .Translate(-self.view.bounds.width-80,0), .Rotate(-1) ], to: [ .Translate(0,0), .Rotate(0) ]).ease(Easing.outSine).play()
```

**Comment by markuswinkler** [comment]
Can confirm that it works, thanks for fixing!
I am familiar with matrix transforms, your argument makes sense.
I am wondering if there is an approach where the order could be decoupled (e.g. the anchor point be automatically fixed to the object center). Especially beginners will struggle with this a lot.
e.g. if there is a rotate in the chain, make sure to apply a translation to (0,0), perform the rotation, and then translate back
