### ISSUE TITLE
Bug: .fromTo with a delay doesn't init right away

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#12]
Same fix needed as with a .from animation:
Kinetic.fromTo(square, duration: 5.7, from: [.Translate(-80,0),.Rotate(-3)], to: [.Translate(0,0),.Rotate(0)]).ease(Easing.outSine).delay(0.6).play()

**Comment by u10int** [comment]
Should be fixed now with my latest changes. I also fixed a lot of other little issues with transform animations I noticed when trying to replicate this preloaded animation: http://greensock.com/circular-preloader. There's a new example in the repo that starts to recreate this, but also shows there's more I'll need to support in order to recreate it 100%.

**Comment by markuswinkler** [comment]
Works!
Big props to recreating all of the greensock functionality!!
