### ISSUE TITLE
Bug: .spring doesn't work with .Translate

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#17]
the moment you use a .spring easing .Translate ignores duration and finishes very fast (without the spring animation)

**Comment by u10int** [comment]
This is the correct functionality as the duration is ignored when using a spring for easing as the easing is what defines the duration of an animation in order to mimic more real-life motion physics. Increasing the friction and/or reducing the tension will increase the duration of the animation.

I'll add this to the docs so it's clearer this week.

**Comment by markuswinkler** [comment]
Makes sense, thanks for the explanation. :+1:
