### ISSUE TITLE
Interpolator issue

### ISSUE THREAD

**Issue by omarojo** [u10int/Kinetic#34]
Im trying to run this example... but the second Interpolation sequence never gets called.
```
let duration = 5.0
let start = 0.2
let end = 0.9
        (start.interpolator(to: end, duration: duration*0.5, function: Easing.type(.sineIn)) { (value) in
            print("\(value)")
            if(value == 0.9){ //reverse
                (end.interpolator(to: start, duration: duration*0.5, function: Easing.type(.backIn)) { (value) in
                    print("\(value)")
                }).run()
            }
            
        }).run()
```

I clearly see the "0.9" printed in the console at the end of the animation. Any idea ?
0.834783264660673
0.843072425218097
0.851380677008584
0.859707158731858
0.868051016404468
0.876411403721092
0.884787482400993
0.89458297075934
0.9

**Comment by u10int** [comment]
The issue is because you're comparing floating point values which doesn't always work as expected due to precision of floats and doubles and small rounding errors that's not apparent when outputting one of these values as a string which uses less precision. This is a common programming concern that's not specific to Swift. You can observe this by outputting the values differently:

```
let duration = 5.0
let start = 0.2
let end = 0.9

start.interpolator(to: end, duration: duration*0.5, function: Easing.type(.sineIn)) { (value) in
	print("\(value), string: \(String(format: "%.20f", value)), end: \(String(format: "%.20f", end))")
	print(value == end)
	
	if value == end { //reverse
		end.interpolator(to: start, duration: duration*0.5, function: Easing.type(.backIn)) { (value) in
			print("\(value)")
		}.run()
	}
}.run()
```

Here's more info:

https://stackoverflow.com/a/43911753
https://stackoverflow.com/questions/43236212/surprising-difference-for-floating-point-arrithmetic-for-double-vs-float
http://www.floating-point-gui.de/errors/comparison/

The solution would be to explicitly provide the type for `start` and `end` as floats:
```
let start: Float = 0.2
let end: Float = 0.9
```

Also, to help resolve this, I've updated the library to add `Float` as an interpolatable type which works as expected alongside using the above change.
