### ISSUE TITLE
Feature request: Antialiasing for rotation

### ISSUE THREAD

**Issue by markuswinkler** [u10int/Kinetic#8]
I noticed that antialiasing for rotation is not turned on.
After some research I stumbled over this post here:
http://stackoverflow.com/questions/8313804/antialiasing-edges-of-uiview-after-transformation-using-calayers-transform

I am not entirely sure what the best (practical) solve for this is
- a global switch
- a setting in the tween options to override a default on 
- semi-automatic depending on object size/complexity

Maybe even a combination of the three. Looking forward to your solve. :)

**Comment by u10int** [comment]
At first I avoided automatically forcing anti-aliasing for all transforms since it should probably be user-controlled, but I agree there should be an easy way to enable and disable for specific tweens. 

I just pushed up a commit that adds this functionality, and edge antialiasing is enabled for all tween objects by default since this is most likely the desired result. If you wish to override this value for a specific Tween or Timeline instance, use the `antialiasing` property on that instance.

**Comment by markuswinkler** [comment]
Just tested, works great!
This kind of implementation has a couple drawbacks though since you need to create an instance first before you can reference bool value.

e.g. you have to write

```
let t=Kinetic.to(square, duration: 1, options: [ .Rotate(1) ])
t.antialiasing = false
t.onComplete { (anim) -> Void in
     t.antialiasing = true
}
t.play()
```

which can add a lot of boilerplate code in case of nested Timeline animations

vs.

```
let t=Kinetic.to(square, duration: 1, options: [ .Rotate(1) ]).autoAntialias(false).play()
```

**Comment by u10int** [comment]
Right now I think I'll leave it as a property rather than chained method as it's probably not something that will ever be disabled very often. Can't think of a reason you'd every want to disable antialiasing for layer transforms other than a slight performance gain for complex animations. I can revisit later if keeping it as a property become more of a pain for a lot of users.

**Comment by markuswinkler** [comment]
Fair enough.
One use case I could think of if you have an animation in a table cell, antialiasing there would affect scrolling, but yeah, it's more on the rare end, especially with current hardware.
